### ISSUE TITLE
Deleting files does not reclaim space in Explorer

### ISSUE THREAD

**Issue by gamlerhart** [openzfsonwindows/ZFSin#19]
Reproduce:
    - Create a bunch of files
    - Delete them
    - Files are gone, but space isn't freed up.

More investigation will follow.

**Comment by lundman** [comment]
How are you measuring the space? zfs list and zpool list should eventually show the disk reclaimed, albeit a bit delayed, since deletion is async.

If you are looking in Explorer etc, I'm sure that won't update as there is no code for it..

**Comment by gamlerhart** [comment]
Clarification: Does not reclaim space in Explorer. (Hmm, unless it's very delayed)
Didn't check zpool/zfs.

Will check again / investigate more.

**Comment by gamlerhart** [comment]
Also doesn't seem to reclaim space in zfs list / zpool.

From logs:
`IRP_MJ_CLEANUP: iocount 0 usecount 2
+zget 4
delete_entry: deleting '\test-file.data'
+zget 60
vnop_remove: may_delete_now is 0, delete_now 0
delete_entry: returning 0`

More investigation will follow. Looks like vnode is consider in use / or cached. (https://github.com/lundman/ZFSin/blob/master/ZFSin/zfs/module/zfs/zfs_vnops.c#L1971)

**Comment by lundman** [comment]
Not sure about that '\\' in the filename, but it is probably just cosmetics.

The real issue is, if `delete_now == 0` it will skip immediate deletion, and place the item on the `unlinked_drain` list, which is purged on next **import**. That is normal for XATTRs, but regular files, we want `delete_now` to be set, so it enters the code that calls `vnode_recycle()` and `zfs_znode_delete()`. 

That is based on `may_delete_now` and the status of `vnode_isinuse()` which probably means it is not 0. But I think that tracks, since Windows opens the file with `delete on close`, so the vnode_isinuse() check probably needs to check iocount is 1 instead of 0.

**Comment by gamlerhart** [comment]
Fixed on master
