### ISSUE TITLE
panic("kernel heap corruption detected"); [debug version - level 460856a] 

### ISSUE THREAD

**Issue by datacore-tlaurent** [openzfsonwindows/ZFSin#205]
When running I/Os I ran into this assertion/panic.  It looks like we are having memory corruption that is being identified in kernel mode where the 0xdeadbeef pattern is checked on every allocation.
I felt that we are having memory alloc issues from the other BSOD I sometimes get where something lookslike it is getting freed twice.

![image](https://user-images.githubusercontent.com/54447336/73464127-6936dc80-434c-11ea-8735-cda5be15190c.png)

The buffer that is being checked during allocation contains 2 mismatching bytes. See the picture.

![image](https://user-images.githubusercontent.com/54447336/73464318-b9ae3a00-434c-11ea-94ca-c2bbc3b56bb9.png)

**Comment by datacore-tlaurent** [comment]
Jorgen: as usual with this sort of issue it is very complicated to find its source.  I was not expecting this in code that should be common code with linux.  Do you have any insight on tools in place in ZFS to troubleshoot this?

**Comment by lundman** [comment]
A bit of background:

spl-kmem.c has the kmem flag:

https://github.com/openzfsonwindows/ZFSin/blob/master/ZFSin/spl/module/spl/spl-kmem.c#L335
```
#ifdef DBG
// can be 0 or KMF_LITE
// or KMF_DEADBEEF | KMF_REDZONE | KMF_CONTENTS
// with or without KMF_AUDIT
int kmem_flags = KMF_DEADBEEF | KMF_REDZONE;
#else
int kmem_flags = 0;
#endif
```

Which controls the amount of debugging that kmem will do, in DEBUG builds we have it do quite a bit, ie, write 0xdeadbeef over the memory on free, and redzone to tag the area just before, and just after memory, to look for buffer under/over-runs.

When things go wrong, it will trigger `kmem_error()`
https://github.com/openzfsonwindows/ZFSin/blob/master/ZFSin/spl/module/spl/spl-kmem.c#L887

which dumps the reason into the kernel print buffer `cbuf` - and stops. You can see the various things it can detect in that call, including duplicate free calls, and it will include information about the memory in question (including stack of allocation, if I ported the stack calls, I think I did).

To dump the `cbuf` to text file, we generally use:

```
dt ZFSin!cbuf
.writemem C:\src\cbuf.txt 0xffff9284`ab010000 L100000
```
Where the address `0xffff9284`ab010000` is the one returned by the `dt` command.

Since kmem comes from illumos/solaris, and is used on osx, I'm pretty confident it is correct, and similarly zio.c is from illumos/linux/freebsd. So I'm betting the issue is with the porting differences to Windows, like that of `mutex_destroy()` being too fast. 

But you are already running that commit, so there is something else at foot. At this point I would take a look at the kmem_error message in `cbuf`  - or alternatively, change kmem_error's `dprintf` into `xprintf` and they'll go to the debug intermediate window. Perhaps we should send to both?

Then we'll find out what memory (I'm guessing kmem_cache zio) and what offset into the buffer was modified. We can then use the offset work out with struct member was changed, and find those locations in the sources and put in traps before the source modifies the memory. Then we'll know where the MAFs is happening and can work on the why.

**Comment by datacore-tlaurent** [comment]
Thanks Jorgen.  I'll take care of the investigation using your information and will post updates here.

**Comment by lundman** [comment]
That's some perfect debugging. Gold Star to those involved!

Yes, it appears offset 0x3e0 is exactly in set_event_guard, so the commit to fix this exact issue is now the cause. Amusing. 
The commit only has atomic +1 and -1, and the change is to 0xdeadbef0, a difference of 1, so that checks out nicely. And it means mutex_destroy() has already called before we enter KeSetEvent(), seems to suggest it isn't the culprit.

**Comment by lundman** [comment]
OK the brain reckons it figured it out, just as I was falling asleep. 

The mutex_enter() logic looks a bit like:

```
	if (InterlockedCompareExchangePointer(&mp->m_owner, 
		thisthread, NULL) != NULL) {
		Status = KeWaitForSingleObject(
			(PRKEVENT)&mp->m_lock,
			Executive,
			KernelMode,
			FALSE,
			NULL
		);
		goto again;
```
We use `InterlockedCompareExchangePointer()` to try to be the first thread to set `owner`. 

The `mutex_exit()` similarly has
```
	mp->m_owner = NULL;
	atomic_inc_32(&mp->set_event_guard);
	KeSetEvent((PRKEVENT)&mp->m_lock, SEMAPHORE_INCREMENT, FALSE);
	atomic_dec_32(&mp->set_event_guard);
```
and it is an easy trap to fall into to think of `KeSetEvent()` as the call that makes other threads resume, and it certainly is for *any thread that is waiting*.

But I made `mutex_enter()` to be efficient when there are no locks held, ie, `InterlockedCompareExchangePointer()` succeeds on first go, and thread never has to block. So in fact, the line that makes other threads "runnable" is 
```
	mp->m_owner = NULL;
```

If that is the case, it would be easy to test it, since we can simply move the `mutex_destroy()` delaying fudge to before the NULL call. Ie:

```
+	atomic_inc_32(&mp->set_event_guard);
	mp->m_owner = NULL;
-	atomic_inc_32(&mp->set_event_guard);
	KeSetEvent((PRKEVENT)&mp->m_lock, SEMAPHORE_INCREMENT, FALSE);
	atomic_dec_32(&mp->set_event_guard);
```

I may rename the struct member `set_event_guard` to something like `num_wakers` and use it as statistics as well, but let's make sure it helps first...

**Comment by lundman** [comment]
Ok, with commits 944823d15a3ea40eea4fa74ebfcda729380d7696 and 082c1d48131c73b86fa623756054c21d3f88b819 I can now complete my zvol tests (with the command lines you supplied) to completion for the first time. It is a bit slow as VM has little memory, but it does eventually finish.

**Comment by datacore-tlaurent** [comment]
Have not seen this very issue again after the fix.  If any other issue related to mutex crops up we will open a different ticket.
